use pkexec first.
use pkexec first and some typo and bash fix.

diff --git a/src/data/bin/manjaro-settings-manager b/src/data/bin/manjaro-settings-manager
--- a/src/data/bin/manjaro-settings-manager
+++ b/src/data/bin/manjaro-settings-manager
@@ -1,14 +1,14 @@
 #!/bin/sh
 
-PROGRAM="/usr/bin/manjaro-settings-manager-gui"
+PROGRAM='/usr/bin/manjaro-settings-manager-gui'
 
-if   [ $(which gksu) ]; then
-	gksu "$PROGRAM" -- $@
-elif [ $(which kdesu) ]; then
-	kdesu "$PROGRAM" -- $@
-elif [ $(which pkexec) ]; then
+if   [ "$(which pkexec)" ]; then
 	pkexec "$PROGRAM" "$@"
+elif [ "$(which gksu)" ]; then
+	gksu "$PROGRAM" -- "$@"
+elif [ "$(which kdesu)" ]; then
+	kdesu "$PROGRAM" -- "$@"
 else
-	echo "error: no pkexec nor sudo frontend application found! Abording..." 1>&2
+	echo "error: no pkexec nor sudo frontend application found! Aborting..." 1>&2
 	exit 1
 fi
