readd sudo apps as polkit makes issues

diff --git a/src/data/bin/manjaro-settings-manager b/src/data/bin/manjaro-settings-manager
--- a/src/data/bin/manjaro-settings-manager
+++ b/src/data/bin/manjaro-settings-manager
@@ -1,8 +1,14 @@
 #!/bin/sh
 
-if [ $(which pkexec) ]; then
-	pkexec "/usr/bin/manjaro-settings-manager-gui" "$@"
+PROGRAMM="/usr/bin/manjaro-settings-manager-gui"
+
+if   [ $(which gksu) ]; then
+	gksu "$PROGRAM" -- $@
+elif [ $(which kdesu) ]; then
+	kdesu "$PROGRAM" -- $@
+elif [ $(which pkexec) ]; then
+	pkexec "$PROGRAM" "$@"
 else
-	echo "error: no pkexec frontend application found! Abording..." 1>&2
+	echo "error: no pkexec nor sudo frontend application found! Abording..." 1>&2
 	exit 1
 fi
